// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/stratumn/alice/grpc/event (interfaces: Emitter_ListenServer)

// Package mockevent is a generated GoMock package.
package mockevent

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	event "github.com/stratumn/alice/grpc/event"
	metadata "google.golang.org/grpc/metadata"
	reflect "reflect"
)

// MockEmitter_ListenServer is a mock of Emitter_ListenServer interface
type MockEmitter_ListenServer struct {
	ctrl     *gomock.Controller
	recorder *MockEmitter_ListenServerMockRecorder
}

// MockEmitter_ListenServerMockRecorder is the mock recorder for MockEmitter_ListenServer
type MockEmitter_ListenServerMockRecorder struct {
	mock *MockEmitter_ListenServer
}

// NewMockEmitter_ListenServer creates a new mock instance
func NewMockEmitter_ListenServer(ctrl *gomock.Controller) *MockEmitter_ListenServer {
	mock := &MockEmitter_ListenServer{ctrl: ctrl}
	mock.recorder = &MockEmitter_ListenServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockEmitter_ListenServer) EXPECT() *MockEmitter_ListenServerMockRecorder {
	return m.recorder
}

// Context mocks base method
func (m *MockEmitter_ListenServer) Context() context.Context {
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context
func (mr *MockEmitter_ListenServerMockRecorder) Context() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockEmitter_ListenServer)(nil).Context))
}

// RecvMsg mocks base method
func (m *MockEmitter_ListenServer) RecvMsg(arg0 interface{}) error {
	ret := m.ctrl.Call(m, "RecvMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg
func (mr *MockEmitter_ListenServerMockRecorder) RecvMsg(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockEmitter_ListenServer)(nil).RecvMsg), arg0)
}

// Send mocks base method
func (m *MockEmitter_ListenServer) Send(arg0 *event.Event) error {
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send
func (mr *MockEmitter_ListenServerMockRecorder) Send(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockEmitter_ListenServer)(nil).Send), arg0)
}

// SendHeader mocks base method
func (m *MockEmitter_ListenServer) SendHeader(arg0 metadata.MD) error {
	ret := m.ctrl.Call(m, "SendHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendHeader indicates an expected call of SendHeader
func (mr *MockEmitter_ListenServerMockRecorder) SendHeader(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendHeader", reflect.TypeOf((*MockEmitter_ListenServer)(nil).SendHeader), arg0)
}

// SendMsg mocks base method
func (m *MockEmitter_ListenServer) SendMsg(arg0 interface{}) error {
	ret := m.ctrl.Call(m, "SendMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg
func (mr *MockEmitter_ListenServerMockRecorder) SendMsg(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockEmitter_ListenServer)(nil).SendMsg), arg0)
}

// SetHeader mocks base method
func (m *MockEmitter_ListenServer) SetHeader(arg0 metadata.MD) error {
	ret := m.ctrl.Call(m, "SetHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHeader indicates an expected call of SetHeader
func (mr *MockEmitter_ListenServerMockRecorder) SetHeader(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeader", reflect.TypeOf((*MockEmitter_ListenServer)(nil).SetHeader), arg0)
}

// SetTrailer mocks base method
func (m *MockEmitter_ListenServer) SetTrailer(arg0 metadata.MD) {
	m.ctrl.Call(m, "SetTrailer", arg0)
}

// SetTrailer indicates an expected call of SetTrailer
func (mr *MockEmitter_ListenServerMockRecorder) SetTrailer(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTrailer", reflect.TypeOf((*MockEmitter_ListenServer)(nil).SetTrailer), arg0)
}
