[[constraint]]
  branch = "master"
  name = "github.com/jhump/protoreflect"

[[constraint]]
  branch = "master"
  name = "github.com/pelletier/go-toml"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "^1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/chzyer/readline"

[[constraint]]
  branch = "master"
  name = "github.com/mohae/deepcopy"

[[constraint]]
  branch = "master"
  name = "github.com/jbenet/go-base58"

[[constraint]]
  branch = "master"
  name = "code.cloudfoundry.org/bytefmt"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "^1.2.2"

[[constraint]]
  name = "github.com/takama/daemon"
  version = "0.11.0"

[[constraint]]
  name = "github.com/golang/mock"
  branch = "master"

[[override]]
  name = "github.com/hpcloud/tail"
  source = "https://github.com/vsco/tail.git"
  revision = "000912af8de2d2b9d184786b4cf4c3542b7884e5"

[[override]] 
  # This is required because Docker claims it needs ^0.4.
  name = "github.com/gogo/protobuf"
  version = "~1.1.1"
  
[[override]]
  name = "go.opencensus.io"
  version = ">=0.18.0"

[[constraint]]
  name = "contrib.go.opencensus.io/exporter/stackdriver"
  version = "0.7.0"
