{
 "title": "Bootstrap",
 "tags": [
  "network",
  "private"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Configuration Updates",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(stratumn_node_views_streams_in{stratumn_node_keys_protocolid=~\"/stratumn/node/bootstrap/private/(coordinator|coordinated)/config/v.+\"}) by (stratumn_node_keys_peerid)",
     "legendFormat": "{{stratumn_node_keys_peerid}}"
    },
    {
     "expr": "sum(stratumn_node_views_streams_out{stratumn_node_keys_protocolid=~\"/stratumn/node/bootstrap/private/(coordinator|coordinated)/config/v.+\"}) by (stratumn_node_keys_peerid)",
     "legendFormat": "{{stratumn_node_keys_peerid}}"
    }
   ]
  },
  {
   "title": "Participants",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "stratumn_node_views_bootstrap_participants"
    }
   ]
  },
  {
   "title": "Proposals",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(stratumn_node_views_streams_in{stratumn_node_keys_protocolid=~\"/stratumn/node/bootstrap/private/(coordinator|coordinated)/propose/v.+\"})"
    }
   ]
  },
  {
   "title": "Votes",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(stratumn_node_views_streams_in{stratumn_node_keys_protocolid=~\"/stratumn/node/bootstrap/private/(coordinator|coordinated)/vote/v.+\"})"
    }
   ]
  },
  {
   "title": "Proposals",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(stratumn_node_views_streams_in{stratumn_node_keys_protocolid=~\"/stratumn/node/bootstrap/private/(coordinator|coordinated)/propose/v.+\"}) by (stratumn_node_keys_peerid)",
     "legendFormat": "{{stratumn_node_keys_peerid}}"
    },
    {
     "expr": "sum(stratumn_node_views_streams_out{stratumn_node_keys_protocolid=~\"/stratumn/node/bootstrap/private/(coordinator|coordinated)/propose/v.+\"}) by (stratumn_node_keys_peerid)",
     "legendFormat": "{{stratumn_node_keys_peerid}}"
    }
   ]
  },
  {
   "title": "Votes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(stratumn_node_views_streams_in{stratumn_node_keys_protocolid=~\"/stratumn/node/bootstrap/private/(coordinator|coordinated)/vote/v.+\"}) by (stratumn_node_keys_peerid)",
     "legendFormat": "{{stratumn_node_keys_peerid}}"
    },
    {
     "expr": "sum(stratumn_node_views_streams_out{stratumn_node_keys_protocolid=~\"/stratumn/node/bootstrap/private/(coordinator|coordinated)/vote/v.+\"}) by (stratumn_node_keys_peerid)",
     "legendFormat": "{{stratumn_node_keys_peerid}}"
    }
   ]
  }
 ]
}