{
 "title": "Chat",
 "tags": [
  "chat",
  "message"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Total Chat Messages Sent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(stratumn_node_views_chat_message_sent) by (stratumn_node_keys_peerid)",
     "legendFormat": "{{stratumn_node_keys_peerid}}"
    }
   ]
  },
  {
   "title": "Total Chat Messages Received",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(stratumn_node_views_chat_message_received) by (stratumn_node_keys_peerid)",
     "legendFormat": "{{stratumn_node_keys_peerid}}"
    }
   ]
  },
  {
   "title": "Total Chat Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(stratumn_node_views_chat_message_error) by (stratumn_node_keys_peerid)",
     "legendFormat": "{{stratumn_node_keys_peerid]}"
    }
   ]
  }
 ]
}