{
 "title": "gRPC API",
 "tags": [
  "grpc",
  "api",
  "cli"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(stratumn_node_views_grpcapi_request_received) by (stratumn_node_keys_grpc_method)",
     "legendFormat": "{{stratumn_node_keys_grpc_method}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(stratumn_node_views_grpcapi_request_error) by (stratumn_node_keys_grpc_method)",
     "legendFormat": "{{stratumn_node_keys_grpc_method}}"
    }
   ]
  },
  {
   "title": "Requests Duration (AVG)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(stratumn_node_views_grpcapi_request_duration_bucket[5m])) by (stratumn_node_keys_grpc_method, le))",
     "legendFormat": "{{stratumn_node_keys_grpc_method}}"
    }
   ]
  },
  {
   "title": "Requests Duration (95th)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(stratumn_node_views_grpcapi_request_duration_bucket[5m])) by (stratumn_node_keys_grpc_method, le))",
     "legendFormat": "{{stratumn_node_keys_grpc_method}}"
    }
   ]
  }
 ]
}