{
 "title": "Indigo Store",
 "tags": [
  "indigo",
  "store",
  "chainscript"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Segments",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(indigo_node_views_indigo_store_segments_created) by (indigo_node_keys_error)",
     "legendFormat": "create={{indigo_node_keys_error}}"
    },
    {
     "expr": "sum(indigo_node_views_indigo_store_segments_received) by (indigo_node_keys_error)",
     "legendFormat": "receive={{indigo_node_keys_error}}"
    }
   ]
  },
  {
   "title": "Fossils",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(indigo_node_views_indigo_fossilizer_fossils) by (indigo_node_keys_error)",
     "legendFormat": "{{indigo_node_keys_error}}"
    }
   ]
  },
  {
   "title": "Sync In",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(indigo_node_views_streams_in{indigo_node_keys_protocolid=~\"/indigo/node/indigo/store/sync/(single|multi)node/v.+\"}) by (indigo_node_keys_peerid)",
     "legendFormat": "{{indigo_node_keys_peerid}}"
    }
   ]
  },
  {
   "title": "Sync Out",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(indigo_node_views_streams_out{indigo_node_keys_protocolid=~\"/indigo/node/indigo/store/sync/(single|multi)node/v.+\"}) by (indigo_node_keys_peerid)",
     "legendFormat": "{{indigo_node_keys_peerid}}"
    }
   ]
  }
 ]
}