{
 "title": "P2P",
 "description": "P2P metrics",
 "tags": [ "p2p" ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "stratumn_node_views_connections",
     "legendFormat": "connections"
    },
    { "expr": "stratumn_node_views_peers", "legendFormat": "connected peers" }
   ]
  },
  {
   "title": "Peers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(stratumn_node_views_streams_in) by (stratumn_node_keys_peerid)",
     "legendFormat": "{{stratumn_node_keys_peerid}} (in)"
    },
    {
     "expr": "sum(stratumn_node_views_streams_out) by (stratumn_node_keys_peerid)",
     "legendFormat": "{{stratumn_node_keys_peerid}} (out)"
    }
   ]
  },
  {
   "title": "Protocols",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(stratumn_node_views_streams_in) by (stratumn_node_keys_protocolid)",
     "legendFormat": "{{stratumn_node_keys_protocolid}} (in)"
    },
    {
     "expr": "sum(stratumn_node_views_streams_out) by (stratumn_node_keys_protocolid)",
     "legendFormat": "{{stratumn_node_keys_protocolid}} (out)"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Latency (AVG)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(stratumn_node_views_latency_bucket[5m])) by (stratumn_node_keys_peerid, le))",
     "legendFormat": "{{stratumn_node_keys_peerid}}"
    }
   ]
  },
  {
   "title": "Latency (95th)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(stratumn_node_views_latency_bucket[5m])) by (stratumn_node_keys_peerid, le))",
     "legendFormat": "{{stratumn_node_keys_peerid}}"
    }
   ]
  },
  { "title": "Bandwidth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Bytes sent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(stratumn_node_views_bandwidth_out[5m])) by (stratumn_node_keys_peerid, le)",
     "legendFormat": "{{stratumn_node_keys_peerid}}"
    }
   ]
  },
  {
   "title": "Bytes received",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(stratumn_node_views_bandwidth_in[5m])) by (stratumn_node_keys_peerid, le)",
     "legendFormat": "{{stratumn_node_keys_peerid}}"
    }
   ]
  }
 ]
}