// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/stratumn/alice/grpc/event/event.proto

/*
Package event is a generated protocol buffer package.

It is generated from these files:
	github.com/stratumn/alice/grpc/event/event.proto

It has these top-level messages:
	ListenReq
	Event
*/
package event

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/stratumn/alice/grpc/ext"
import _ "github.com/golang/protobuf/protoc-gen-go/descriptor"

import (
	context "context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The Listen request message.
type ListenReq struct {
}

func (m *ListenReq) Reset()                    { *m = ListenReq{} }
func (m *ListenReq) String() string            { return proto.CompactTextString(m) }
func (*ListenReq) ProtoMessage()               {}
func (*ListenReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// The Event message containing what should be displayed, with optional
// display customization (if supported by the listener).
type Event struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	Color   string `protobuf:"bytes,2,opt,name=color" json:"color,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Event) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Event) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func init() {
	proto.RegisterType((*ListenReq)(nil), "stratumn.alice.grpc.event.ListenReq")
	proto.RegisterType((*Event)(nil), "stratumn.alice.grpc.event.Event")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for MyEventService service

type MyEventServiceClient interface {
	// Listen starts listening to events from MyEventService.
	Listen(ctx context.Context, in *ListenReq, opts ...grpc.CallOption) (MyEventService_ListenClient, error)
}

type myEventServiceClient struct {
	cc *grpc.ClientConn
}

func NewMyEventServiceClient(cc *grpc.ClientConn) MyEventServiceClient {
	return &myEventServiceClient{cc}
}

func (c *myEventServiceClient) Listen(ctx context.Context, in *ListenReq, opts ...grpc.CallOption) (MyEventService_ListenClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_MyEventService_serviceDesc.Streams[0], c.cc, "/stratumn.alice.grpc.event.MyEventService/Listen", opts...)
	if err != nil {
		return nil, err
	}
	x := &myEventServiceListenClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MyEventService_ListenClient interface {
	Recv() (*Event, error)
	grpc.ClientStream
}

type myEventServiceListenClient struct {
	grpc.ClientStream
}

func (x *myEventServiceListenClient) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for MyEventService service

type MyEventServiceServer interface {
	// Listen starts listening to events from MyEventService.
	Listen(*ListenReq, MyEventService_ListenServer) error
}

func RegisterMyEventServiceServer(s *grpc.Server, srv MyEventServiceServer) {
	s.RegisterService(&_MyEventService_serviceDesc, srv)
}

func _MyEventService_Listen_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListenReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MyEventServiceServer).Listen(m, &myEventServiceListenServer{stream})
}

type MyEventService_ListenServer interface {
	Send(*Event) error
	grpc.ServerStream
}

type myEventServiceListenServer struct {
	grpc.ServerStream
}

func (x *myEventServiceListenServer) Send(m *Event) error {
	return x.ServerStream.SendMsg(m)
}

var _MyEventService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "stratumn.alice.grpc.event.MyEventService",
	HandlerType: (*MyEventServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Listen",
			Handler:       _MyEventService_Listen_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "github.com/stratumn/alice/grpc/event/event.proto",
}

func init() { proto.RegisterFile("github.com/stratumn/alice/grpc/event/event.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 315 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xbd, 0x4a, 0x03, 0x41,
	0x10, 0x80, 0x39, 0x21, 0x91, 0xac, 0x20, 0x78, 0xd5, 0x26, 0xd5, 0x10, 0x04, 0x45, 0xc2, 0x6e,
	0x50, 0x3b, 0xbb, 0x88, 0x85, 0xa2, 0x4d, 0xec, 0xec, 0xee, 0x67, 0xb2, 0x77, 0x70, 0x97, 0x39,
	0x77, 0xe7, 0x82, 0xa9, 0x04, 0x2b, 0x9f, 0xc2, 0x22, 0x95, 0x2f, 0x90, 0x2a, 0x2f, 0x27, 0xb7,
	0x97, 0xd8, 0xf9, 0x53, 0xdc, 0xc0, 0xed, 0x7c, 0xf3, 0xcd, 0xec, 0xac, 0x18, 0x9b, 0x9c, 0xb3,
	0x3a, 0x56, 0x09, 0x95, 0xda, 0xb1, 0x8d, 0xb8, 0x2e, 0xe7, 0x3a, 0x2a, 0xf2, 0x04, 0xb5, 0xb1,
	0x55, 0xa2, 0x71, 0x81, 0x73, 0x6e, 0xa3, 0xaa, 0x2c, 0x31, 0x85, 0xfd, 0x1d, 0xa6, 0x3c, 0xa6,
	0x1a, 0x4c, 0x79, 0x60, 0x30, 0xfa, 0x4b, 0xf6, 0xc2, 0xcd, 0xd7, 0x8a, 0x06, 0x60, 0x88, 0x4c,
	0x81, 0xda, 0xff, 0xc5, 0xf5, 0x4c, 0xa7, 0xe8, 0x12, 0x9b, 0x57, 0x4c, 0xb6, 0x25, 0x86, 0x07,
	0xa2, 0x77, 0x9f, 0x3b, 0xc6, 0xf9, 0x14, 0x9f, 0x87, 0x1f, 0x81, 0xe8, 0xdc, 0x34, 0x6d, 0xc2,
	0x5b, 0xb1, 0x5f, 0xa2, 0x73, 0x91, 0x41, 0x19, 0x40, 0x70, 0xda, 0x9b, 0xe8, 0xd5, 0x46, 0x9e,
	0xf8, 0x1c, 0x6c, 0x13, 0xc0, 0x04, 0x31, 0x42, 0x9a, 0xbb, 0xaa, 0x88, 0x96, 0x98, 0x02, 0x59,
	0x28, 0xc8, 0x18, 0x4c, 0x3f, 0x37, 0x32, 0x98, 0xee, 0xea, 0xc3, 0x3b, 0xd1, 0x49, 0xa8, 0x20,
	0x2b, 0xf7, 0xbc, 0xe8, 0x72, 0xb5, 0x91, 0xe3, 0xeb, 0xe6, 0x00, 0x38, 0x8b, 0x18, 0x5c, 0x46,
	0x75, 0x91, 0x36, 0xa6, 0xda, 0x61, 0xda, 0x48, 0xb7, 0x46, 0xe0, 0x0c, 0x77, 0xbd, 0xa6, 0xad,
	0xe2, 0xfc, 0x55, 0x1c, 0x3e, 0x2c, 0xfd, 0x14, 0x8f, 0x68, 0x17, 0x79, 0x82, 0x61, 0x29, 0xba,
	0xed, 0xfc, 0xe1, 0xb1, 0xfa, 0x71, 0x6b, 0xea, 0xfb, 0x8a, 0x03, 0xf8, 0x85, 0xf2, 0xe2, 0x61,
	0xff, 0x6d, 0x2d, 0x8f, 0xda, 0x02, 0x98, 0x91, 0x05, 0x9f, 0x73, 0xef, 0x6b, 0x19, 0x8c, 0x83,
	0xc9, 0xe8, 0xe9, 0xec, 0x3f, 0xaf, 0x79, 0xe5, 0x63, 0xdc, 0xf5, 0x3b, 0xbe, 0xf8, 0x0a, 0x00,
	0x00, 0xff, 0xff, 0xc2, 0x67, 0x11, 0xfb, 0x02, 0x02, 0x00, 0x00,
}
