// Copyright © 2017-2018 Stratumn SAS
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package transaction

import (
	"testing"

	pb "github.com/stratumn/alice/pb/coin"
	"github.com/stretchr/testify/require"

	peer "gx/ipfs/Qma7H6RW8wRrfZpNSXwxYGcd1E149s42FpWNpDNieSVrnU/go-libp2p-peer"
	ic "gx/ipfs/QmaPbCnUMBohSGo3KnxEa2bHqyJVVeEEcwtqJAYxerieBo/go-libp2p-crypto"
)

var txSenderPrivateKey ic.PrivKey
var txSenderPublicKey ic.PubKey

// TxSenderPID is the sender in transactions generated by NewTransaction.
var TxSenderPID peer.ID

// TxRecipientPID is the recipient in transactions generated by NewTransaction.
var TxRecipientPID peer.ID

func init() {
	sk, pk, err := ic.GenerateKeyPair(ic.Ed25519, 0)
	if err != nil {
		panic(err)
	}

	txSenderPrivateKey = sk
	txSenderPublicKey = pk

	pid, err := peer.IDFromPrivateKey(txSenderPrivateKey)
	if err != nil {
		panic(err)
	}

	TxSenderPID = pid

	pid, err = peer.IDB58Decode("QmYgPDzgtjRQFC4poxTD8fgVnVVf3wHQPjrmyph8Wy8ZmQ")
	if err != nil {
		panic(err)
	}

	TxRecipientPID = pid
}

// NewKeyPair returns key pair and peer ID.
func NewKeyPair() (ic.PrivKey, ic.PubKey, []byte, error) {
	sk, pk, err := ic.GenerateKeyPair(ic.Ed25519, 0)
	if err != nil {
		return nil, nil, nil, err
	}

	pid, err := peer.IDFromPrivateKey(sk)
	if err != nil {
		return nil, nil, nil, err
	}

	return sk, pk, []byte(pid), nil
}

// NewTransaction creates a properly signed transaction.
func NewTransaction(t *testing.T, value, fee, nonce uint64) *pb.Transaction {
	tx := &pb.Transaction{
		From:  []byte(TxSenderPID),
		To:    []byte(TxRecipientPID),
		Value: value,
		Fee:   fee,
		Nonce: nonce,
	}

	b, err := tx.Marshal()
	require.NoError(t, err, "tx.Marshal()")

	sig, err := txSenderPrivateKey.Sign(b)
	require.NoError(t, err, "testSenderPrivateKey.Sign(b)")

	pk, err := txSenderPublicKey.Bytes()
	require.NoError(t, err, "testSenderPublicKey.Bytes()")

	tx.Signature = &pb.Signature{
		KeyType:   pb.KeyType_Ed25519,
		PublicKey: pk,
		Signature: sig,
	}

	return tx
}

// NewTransactions creates a set of random transactions.
func NewTransactions(t *testing.T, txCount int) []*pb.Transaction {
	txs := make([]*pb.Transaction, txCount)
	for i := 0; i < txCount; i++ {
		txs[i] = NewTransaction(t, 4, 2, uint64(i))
	}
	return txs
}

// NewRewardTransaction creates a new reward transaction.
func NewRewardTransaction(t *testing.T, value uint64) *pb.Transaction {
	return &pb.Transaction{
		To:    []byte(TxRecipientPID),
		Value: value,
	}
}
