// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/stratumn/alice/core/app/bootstrap/grpc/bootstrap.proto

/*
	Package grpc is a generated protocol buffer package.

	It is generated from these files:
		github.com/stratumn/alice/core/app/bootstrap/grpc/bootstrap.proto

	It has these top-level messages:
*/
package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/stratumn/alice/grpc/ext"
import stratumn_alice_core_app_bootstrap_pb "github.com/stratumn/alice/core/app/bootstrap/pb"

import context "context"
import grpc1 "google.golang.org/grpc"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc1.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc1.SupportPackageIsVersion4

// Client API for Bootstrap service

type BootstrapClient interface {
	// Propose adding a node to the network.
	AddNode(ctx context.Context, in *stratumn_alice_core_app_bootstrap_pb.NodeIdentity, opts ...grpc1.CallOption) (*stratumn_alice_core_app_bootstrap_pb.Ack, error)
	// Propose removing a node from the network.
	RemoveNode(ctx context.Context, in *stratumn_alice_core_app_bootstrap_pb.NodeIdentity, opts ...grpc1.CallOption) (*stratumn_alice_core_app_bootstrap_pb.Ack, error)
	// Accept a proposal to add or remove a network node.
	Accept(ctx context.Context, in *stratumn_alice_core_app_bootstrap_pb.PeerID, opts ...grpc1.CallOption) (*stratumn_alice_core_app_bootstrap_pb.Ack, error)
	// Reject a proposal to add or remove a network node.
	Reject(ctx context.Context, in *stratumn_alice_core_app_bootstrap_pb.PeerID, opts ...grpc1.CallOption) (*stratumn_alice_core_app_bootstrap_pb.Ack, error)
	// List pending proposals to add or remove a network node.
	List(ctx context.Context, in *stratumn_alice_core_app_bootstrap_pb.Filter, opts ...grpc1.CallOption) (Bootstrap_ListClient, error)
	// Complete the network bootstrap phase.
	Complete(ctx context.Context, in *stratumn_alice_core_app_bootstrap_pb.CompleteReq, opts ...grpc1.CallOption) (*stratumn_alice_core_app_bootstrap_pb.Ack, error)
}

type bootstrapClient struct {
	cc *grpc1.ClientConn
}

func NewBootstrapClient(cc *grpc1.ClientConn) BootstrapClient {
	return &bootstrapClient{cc}
}

func (c *bootstrapClient) AddNode(ctx context.Context, in *stratumn_alice_core_app_bootstrap_pb.NodeIdentity, opts ...grpc1.CallOption) (*stratumn_alice_core_app_bootstrap_pb.Ack, error) {
	out := new(stratumn_alice_core_app_bootstrap_pb.Ack)
	err := grpc1.Invoke(ctx, "/stratumn.alice.core.app.bootstrap.grpc.Bootstrap/AddNode", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bootstrapClient) RemoveNode(ctx context.Context, in *stratumn_alice_core_app_bootstrap_pb.NodeIdentity, opts ...grpc1.CallOption) (*stratumn_alice_core_app_bootstrap_pb.Ack, error) {
	out := new(stratumn_alice_core_app_bootstrap_pb.Ack)
	err := grpc1.Invoke(ctx, "/stratumn.alice.core.app.bootstrap.grpc.Bootstrap/RemoveNode", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bootstrapClient) Accept(ctx context.Context, in *stratumn_alice_core_app_bootstrap_pb.PeerID, opts ...grpc1.CallOption) (*stratumn_alice_core_app_bootstrap_pb.Ack, error) {
	out := new(stratumn_alice_core_app_bootstrap_pb.Ack)
	err := grpc1.Invoke(ctx, "/stratumn.alice.core.app.bootstrap.grpc.Bootstrap/Accept", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bootstrapClient) Reject(ctx context.Context, in *stratumn_alice_core_app_bootstrap_pb.PeerID, opts ...grpc1.CallOption) (*stratumn_alice_core_app_bootstrap_pb.Ack, error) {
	out := new(stratumn_alice_core_app_bootstrap_pb.Ack)
	err := grpc1.Invoke(ctx, "/stratumn.alice.core.app.bootstrap.grpc.Bootstrap/Reject", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bootstrapClient) List(ctx context.Context, in *stratumn_alice_core_app_bootstrap_pb.Filter, opts ...grpc1.CallOption) (Bootstrap_ListClient, error) {
	stream, err := grpc1.NewClientStream(ctx, &_Bootstrap_serviceDesc.Streams[0], c.cc, "/stratumn.alice.core.app.bootstrap.grpc.Bootstrap/List", opts...)
	if err != nil {
		return nil, err
	}
	x := &bootstrapListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Bootstrap_ListClient interface {
	Recv() (*stratumn_alice_core_app_bootstrap_pb.UpdateProposal, error)
	grpc1.ClientStream
}

type bootstrapListClient struct {
	grpc1.ClientStream
}

func (x *bootstrapListClient) Recv() (*stratumn_alice_core_app_bootstrap_pb.UpdateProposal, error) {
	m := new(stratumn_alice_core_app_bootstrap_pb.UpdateProposal)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *bootstrapClient) Complete(ctx context.Context, in *stratumn_alice_core_app_bootstrap_pb.CompleteReq, opts ...grpc1.CallOption) (*stratumn_alice_core_app_bootstrap_pb.Ack, error) {
	out := new(stratumn_alice_core_app_bootstrap_pb.Ack)
	err := grpc1.Invoke(ctx, "/stratumn.alice.core.app.bootstrap.grpc.Bootstrap/Complete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Bootstrap service

type BootstrapServer interface {
	// Propose adding a node to the network.
	AddNode(context.Context, *stratumn_alice_core_app_bootstrap_pb.NodeIdentity) (*stratumn_alice_core_app_bootstrap_pb.Ack, error)
	// Propose removing a node from the network.
	RemoveNode(context.Context, *stratumn_alice_core_app_bootstrap_pb.NodeIdentity) (*stratumn_alice_core_app_bootstrap_pb.Ack, error)
	// Accept a proposal to add or remove a network node.
	Accept(context.Context, *stratumn_alice_core_app_bootstrap_pb.PeerID) (*stratumn_alice_core_app_bootstrap_pb.Ack, error)
	// Reject a proposal to add or remove a network node.
	Reject(context.Context, *stratumn_alice_core_app_bootstrap_pb.PeerID) (*stratumn_alice_core_app_bootstrap_pb.Ack, error)
	// List pending proposals to add or remove a network node.
	List(*stratumn_alice_core_app_bootstrap_pb.Filter, Bootstrap_ListServer) error
	// Complete the network bootstrap phase.
	Complete(context.Context, *stratumn_alice_core_app_bootstrap_pb.CompleteReq) (*stratumn_alice_core_app_bootstrap_pb.Ack, error)
}

func RegisterBootstrapServer(s *grpc1.Server, srv BootstrapServer) {
	s.RegisterService(&_Bootstrap_serviceDesc, srv)
}

func _Bootstrap_AddNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(stratumn_alice_core_app_bootstrap_pb.NodeIdentity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BootstrapServer).AddNode(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stratumn.alice.core.app.bootstrap.grpc.Bootstrap/AddNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BootstrapServer).AddNode(ctx, req.(*stratumn_alice_core_app_bootstrap_pb.NodeIdentity))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bootstrap_RemoveNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(stratumn_alice_core_app_bootstrap_pb.NodeIdentity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BootstrapServer).RemoveNode(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stratumn.alice.core.app.bootstrap.grpc.Bootstrap/RemoveNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BootstrapServer).RemoveNode(ctx, req.(*stratumn_alice_core_app_bootstrap_pb.NodeIdentity))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bootstrap_Accept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(stratumn_alice_core_app_bootstrap_pb.PeerID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BootstrapServer).Accept(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stratumn.alice.core.app.bootstrap.grpc.Bootstrap/Accept",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BootstrapServer).Accept(ctx, req.(*stratumn_alice_core_app_bootstrap_pb.PeerID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bootstrap_Reject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(stratumn_alice_core_app_bootstrap_pb.PeerID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BootstrapServer).Reject(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stratumn.alice.core.app.bootstrap.grpc.Bootstrap/Reject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BootstrapServer).Reject(ctx, req.(*stratumn_alice_core_app_bootstrap_pb.PeerID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bootstrap_List_Handler(srv interface{}, stream grpc1.ServerStream) error {
	m := new(stratumn_alice_core_app_bootstrap_pb.Filter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BootstrapServer).List(m, &bootstrapListServer{stream})
}

type Bootstrap_ListServer interface {
	Send(*stratumn_alice_core_app_bootstrap_pb.UpdateProposal) error
	grpc1.ServerStream
}

type bootstrapListServer struct {
	grpc1.ServerStream
}

func (x *bootstrapListServer) Send(m *stratumn_alice_core_app_bootstrap_pb.UpdateProposal) error {
	return x.ServerStream.SendMsg(m)
}

func _Bootstrap_Complete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(stratumn_alice_core_app_bootstrap_pb.CompleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BootstrapServer).Complete(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stratumn.alice.core.app.bootstrap.grpc.Bootstrap/Complete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BootstrapServer).Complete(ctx, req.(*stratumn_alice_core_app_bootstrap_pb.CompleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Bootstrap_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "stratumn.alice.core.app.bootstrap.grpc.Bootstrap",
	HandlerType: (*BootstrapServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "AddNode",
			Handler:    _Bootstrap_AddNode_Handler,
		},
		{
			MethodName: "RemoveNode",
			Handler:    _Bootstrap_RemoveNode_Handler,
		},
		{
			MethodName: "Accept",
			Handler:    _Bootstrap_Accept_Handler,
		},
		{
			MethodName: "Reject",
			Handler:    _Bootstrap_Reject_Handler,
		},
		{
			MethodName: "Complete",
			Handler:    _Bootstrap_Complete_Handler,
		},
	},
	Streams: []grpc1.StreamDesc{
		{
			StreamName:    "List",
			Handler:       _Bootstrap_List_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "github.com/stratumn/alice/core/app/bootstrap/grpc/bootstrap.proto",
}

func init() {
	proto.RegisterFile("github.com/stratumn/alice/core/app/bootstrap/grpc/bootstrap.proto", fileDescriptorBootstrap)
}

var fileDescriptorBootstrap = []byte{
	// 420 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0xd4, 0x4f, 0x8b, 0xd3, 0x40,
	0x18, 0x06, 0x70, 0x07, 0x64, 0x57, 0x73, 0xcc, 0x29, 0xe4, 0x10, 0x86, 0x45, 0x64, 0x85, 0x32,
	0x71, 0x57, 0xdd, 0x83, 0x1e, 0x24, 0xab, 0x88, 0x0b, 0x22, 0xa5, 0xe0, 0xc5, 0xdb, 0x64, 0xe6,
	0xb5, 0x8d, 0x4d, 0xf2, 0xbe, 0x4e, 0xa6, 0xfe, 0xb9, 0xe6, 0x23, 0x78, 0xaa, 0xdf, 0xc0, 0xb3,
	0x90, 0xef, 0xe0, 0xd1, 0x8f, 0x20, 0xf5, 0x8b, 0xc8, 0x24, 0xc6, 0x56, 0x41, 0x9a, 0x1c, 0xdc,
	0x43, 0x0b, 0x6d, 0xde, 0x67, 0x9e, 0x1f, 0x61, 0x66, 0xbc, 0x64, 0x9e, 0xd9, 0xc5, 0x2a, 0x15,
	0x0a, 0x8b, 0xb8, 0xb2, 0x46, 0xda, 0x55, 0x51, 0xc6, 0x32, 0xcf, 0x14, 0xc4, 0x0a, 0x0d, 0xc4,
	0x92, 0x28, 0x4e, 0x11, 0xad, 0x7b, 0x46, 0xf1, 0xdc, 0x90, 0xda, 0xfe, 0x14, 0x64, 0xd0, 0xa2,
	0x7f, 0xb3, 0xcf, 0x89, 0x36, 0x27, 0x5c, 0x4e, 0x48, 0x22, 0xb1, 0x1d, 0x74, 0xb9, 0x70, 0xf2,
	0xef, 0xaa, 0x76, 0x5d, 0x78, 0x6f, 0xdd, 0xa7, 0x5b, 0x35, 0x7c, 0x38, 0x0a, 0x46, 0xe9, 0xdf,
	0xac, 0xd3, 0x2f, 0x87, 0xde, 0xf5, 0xf3, 0xfe, 0x3f, 0xff, 0x23, 0xf3, 0x0e, 0x13, 0xad, 0x9f,
	0xa3, 0x06, 0xff, 0x54, 0xec, 0x17, 0x53, 0x2a, 0xdc, 0xec, 0x85, 0x86, 0xd2, 0x66, 0xf6, 0x43,
	0x78, 0x6b, 0x58, 0x26, 0x51, 0xcb, 0xa3, 0xe3, 0xba, 0x09, 0x6e, 0x4c, 0x0d, 0x12, 0x56, 0xc0,
	0xa5, 0xd6, 0x59, 0x39, 0xe7, 0x92, 0x97, 0xa8, 0x81, 0x5b, 0xe4, 0x76, 0x01, 0xbc, 0x04, 0xfb,
	0x0e, 0xcd, 0xd2, 0xff, 0xc4, 0x3c, 0x6f, 0x06, 0x05, 0xbe, 0x85, 0xcb, 0x70, 0x4d, 0xea, 0x26,
	0x38, 0xee, 0x5d, 0xc6, 0xd5, 0xee, 0xc8, 0x5e, 0x19, 0x2c, 0xfe, 0xb0, 0xad, 0x99, 0x77, 0x90,
	0x28, 0x05, 0x64, 0xfd, 0xc9, 0xb0, 0x8e, 0x29, 0x80, 0xb9, 0x78, 0x3c, 0x46, 0x74, 0xaf, 0x6e,
	0x82, 0x93, 0xae, 0x84, 0x4b, 0x4e, 0x2d, 0x4d, 0xe6, 0xee, 0x2d, 0x49, 0xad, 0x39, 0x9a, 0x4e,
	0x09, 0xce, 0xd8, 0xa9, 0x5a, 0x6b, 0x4b, 0x9b, 0xc1, 0x6b, 0x50, 0xff, 0x9b, 0xd6, 0x95, 0x8c,
	0xa1, 0x7d, 0x66, 0xde, 0xd5, 0x67, 0x59, 0x35, 0x18, 0xf6, 0x24, 0xcb, 0x2d, 0x98, 0xf0, 0xee,
	0xb0, 0xe9, 0x17, 0xa4, 0xa5, 0x85, 0xe9, 0x2f, 0xcc, 0xd1, 0xfd, 0xba, 0x09, 0xce, 0x5c, 0x1b,
	0x27, 0x28, 0xdb, 0x6d, 0xd6, 0x3b, 0xab, 0x7d, 0xd0, 0xdb, 0xcc, 0x9d, 0x88, 0x6b, 0x8f, 0xb0,
	0xa0, 0x1c, 0x2c, 0xf8, 0x27, 0xc3, 0x00, 0xfd, 0xfc, 0x0c, 0xde, 0x8c, 0x3e, 0x11, 0x7d, 0x76,
	0x77, 0x97, 0xf1, 0xdf, 0xa3, 0x9c, 0x16, 0xb2, 0x82, 0xf3, 0xa7, 0x5f, 0x37, 0x11, 0xfb, 0xb6,
	0x89, 0xd8, 0xf7, 0x4d, 0xc4, 0xd6, 0x3f, 0xa2, 0x2b, 0x2f, 0xcf, 0x46, 0x5f, 0x50, 0x0f, 0xdc,
	0x57, 0x7a, 0xd0, 0xde, 0x02, 0x77, 0x7e, 0x06, 0x00, 0x00, 0xff, 0xff, 0xd8, 0x6e, 0x3e, 0x31,
	0xe1, 0x04, 0x00, 0x00,
}
