// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/stratumn/go-node/app/indigo/grpc/store/store.proto

/*
	Package store is a generated protocol buffer package.

	It is generated from these files:
		github.com/stratumn/go-node/app/indigo/grpc/store/store.proto

	It has these top-level messages:
		InfoReq
		InfoResp
		SegmentFilter
		MapIDs
		MapFilter
		AddEvidenceReq
		AddEvidenceResp
*/
package store

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/stratumn/go-node/cli/grpc/ext"
import stratumn_node_app_indigo_store "github.com/stratumn/go-node/app/indigo/pb/store"

import context "context"
import grpc "google.golang.org/grpc"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type InfoReq struct {
}

func (m *InfoReq) Reset()                    { *m = InfoReq{} }
func (m *InfoReq) String() string            { return proto.CompactTextString(m) }
func (*InfoReq) ProtoMessage()               {}
func (*InfoReq) Descriptor() ([]byte, []int) { return fileDescriptorStore, []int{0} }

type InfoResp struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *InfoResp) Reset()                    { *m = InfoResp{} }
func (m *InfoResp) String() string            { return proto.CompactTextString(m) }
func (*InfoResp) ProtoMessage()               {}
func (*InfoResp) Descriptor() ([]byte, []int) { return fileDescriptorStore, []int{1} }

func (m *InfoResp) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type SegmentFilter struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *SegmentFilter) Reset()                    { *m = SegmentFilter{} }
func (m *SegmentFilter) String() string            { return proto.CompactTextString(m) }
func (*SegmentFilter) ProtoMessage()               {}
func (*SegmentFilter) Descriptor() ([]byte, []int) { return fileDescriptorStore, []int{2} }

func (m *SegmentFilter) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type MapIDs struct {
	MapIds []string `protobuf:"bytes,1,rep,name=map_ids,json=mapIds" json:"map_ids,omitempty"`
}

func (m *MapIDs) Reset()                    { *m = MapIDs{} }
func (m *MapIDs) String() string            { return proto.CompactTextString(m) }
func (*MapIDs) ProtoMessage()               {}
func (*MapIDs) Descriptor() ([]byte, []int) { return fileDescriptorStore, []int{3} }

func (m *MapIDs) GetMapIds() []string {
	if m != nil {
		return m.MapIds
	}
	return nil
}

type MapFilter struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *MapFilter) Reset()                    { *m = MapFilter{} }
func (m *MapFilter) String() string            { return proto.CompactTextString(m) }
func (*MapFilter) ProtoMessage()               {}
func (*MapFilter) Descriptor() ([]byte, []int) { return fileDescriptorStore, []int{4} }

func (m *MapFilter) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type AddEvidenceReq struct {
	LinkHash *stratumn_node_app_indigo_store.LinkHash `protobuf:"bytes,1,opt,name=link_hash,json=linkHash" json:"link_hash,omitempty"`
	Evidence *stratumn_node_app_indigo_store.Evidence `protobuf:"bytes,2,opt,name=evidence" json:"evidence,omitempty"`
}

func (m *AddEvidenceReq) Reset()                    { *m = AddEvidenceReq{} }
func (m *AddEvidenceReq) String() string            { return proto.CompactTextString(m) }
func (*AddEvidenceReq) ProtoMessage()               {}
func (*AddEvidenceReq) Descriptor() ([]byte, []int) { return fileDescriptorStore, []int{5} }

func (m *AddEvidenceReq) GetLinkHash() *stratumn_node_app_indigo_store.LinkHash {
	if m != nil {
		return m.LinkHash
	}
	return nil
}

func (m *AddEvidenceReq) GetEvidence() *stratumn_node_app_indigo_store.Evidence {
	if m != nil {
		return m.Evidence
	}
	return nil
}

type AddEvidenceResp struct {
}

func (m *AddEvidenceResp) Reset()                    { *m = AddEvidenceResp{} }
func (m *AddEvidenceResp) String() string            { return proto.CompactTextString(m) }
func (*AddEvidenceResp) ProtoMessage()               {}
func (*AddEvidenceResp) Descriptor() ([]byte, []int) { return fileDescriptorStore, []int{6} }

func init() {
	proto.RegisterType((*InfoReq)(nil), "stratumn.node.app.indigo.store.grpc.InfoReq")
	proto.RegisterType((*InfoResp)(nil), "stratumn.node.app.indigo.store.grpc.InfoResp")
	proto.RegisterType((*SegmentFilter)(nil), "stratumn.node.app.indigo.store.grpc.SegmentFilter")
	proto.RegisterType((*MapIDs)(nil), "stratumn.node.app.indigo.store.grpc.MapIDs")
	proto.RegisterType((*MapFilter)(nil), "stratumn.node.app.indigo.store.grpc.MapFilter")
	proto.RegisterType((*AddEvidenceReq)(nil), "stratumn.node.app.indigo.store.grpc.AddEvidenceReq")
	proto.RegisterType((*AddEvidenceResp)(nil), "stratumn.node.app.indigo.store.grpc.AddEvidenceResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for IndigoStore service

type IndigoStoreClient interface {
	// Get store information.
	GetInfo(ctx context.Context, in *InfoReq, opts ...grpc.CallOption) (*InfoResp, error)
	// Create a link.
	CreateLink(ctx context.Context, in *stratumn_node_app_indigo_store.Link, opts ...grpc.CallOption) (*stratumn_node_app_indigo_store.LinkHash, error)
	// Get a segment.
	GetSegment(ctx context.Context, in *stratumn_node_app_indigo_store.LinkHash, opts ...grpc.CallOption) (*stratumn_node_app_indigo_store.Segment, error)
	// Find segments.
	FindSegments(ctx context.Context, in *SegmentFilter, opts ...grpc.CallOption) (*stratumn_node_app_indigo_store.Segments, error)
	// Get map IDs.
	GetMapIDs(ctx context.Context, in *MapFilter, opts ...grpc.CallOption) (*MapIDs, error)
	// Add evidence to a segment.
	AddEvidence(ctx context.Context, in *AddEvidenceReq, opts ...grpc.CallOption) (*AddEvidenceResp, error)
	// Get segment evidences.
	GetEvidences(ctx context.Context, in *stratumn_node_app_indigo_store.LinkHash, opts ...grpc.CallOption) (*stratumn_node_app_indigo_store.Evidences, error)
}

type indigoStoreClient struct {
	cc *grpc.ClientConn
}

func NewIndigoStoreClient(cc *grpc.ClientConn) IndigoStoreClient {
	return &indigoStoreClient{cc}
}

func (c *indigoStoreClient) GetInfo(ctx context.Context, in *InfoReq, opts ...grpc.CallOption) (*InfoResp, error) {
	out := new(InfoResp)
	err := grpc.Invoke(ctx, "/stratumn.node.app.indigo.store.grpc.IndigoStore/GetInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indigoStoreClient) CreateLink(ctx context.Context, in *stratumn_node_app_indigo_store.Link, opts ...grpc.CallOption) (*stratumn_node_app_indigo_store.LinkHash, error) {
	out := new(stratumn_node_app_indigo_store.LinkHash)
	err := grpc.Invoke(ctx, "/stratumn.node.app.indigo.store.grpc.IndigoStore/CreateLink", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indigoStoreClient) GetSegment(ctx context.Context, in *stratumn_node_app_indigo_store.LinkHash, opts ...grpc.CallOption) (*stratumn_node_app_indigo_store.Segment, error) {
	out := new(stratumn_node_app_indigo_store.Segment)
	err := grpc.Invoke(ctx, "/stratumn.node.app.indigo.store.grpc.IndigoStore/GetSegment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indigoStoreClient) FindSegments(ctx context.Context, in *SegmentFilter, opts ...grpc.CallOption) (*stratumn_node_app_indigo_store.Segments, error) {
	out := new(stratumn_node_app_indigo_store.Segments)
	err := grpc.Invoke(ctx, "/stratumn.node.app.indigo.store.grpc.IndigoStore/FindSegments", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indigoStoreClient) GetMapIDs(ctx context.Context, in *MapFilter, opts ...grpc.CallOption) (*MapIDs, error) {
	out := new(MapIDs)
	err := grpc.Invoke(ctx, "/stratumn.node.app.indigo.store.grpc.IndigoStore/GetMapIDs", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indigoStoreClient) AddEvidence(ctx context.Context, in *AddEvidenceReq, opts ...grpc.CallOption) (*AddEvidenceResp, error) {
	out := new(AddEvidenceResp)
	err := grpc.Invoke(ctx, "/stratumn.node.app.indigo.store.grpc.IndigoStore/AddEvidence", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indigoStoreClient) GetEvidences(ctx context.Context, in *stratumn_node_app_indigo_store.LinkHash, opts ...grpc.CallOption) (*stratumn_node_app_indigo_store.Evidences, error) {
	out := new(stratumn_node_app_indigo_store.Evidences)
	err := grpc.Invoke(ctx, "/stratumn.node.app.indigo.store.grpc.IndigoStore/GetEvidences", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for IndigoStore service

type IndigoStoreServer interface {
	// Get store information.
	GetInfo(context.Context, *InfoReq) (*InfoResp, error)
	// Create a link.
	CreateLink(context.Context, *stratumn_node_app_indigo_store.Link) (*stratumn_node_app_indigo_store.LinkHash, error)
	// Get a segment.
	GetSegment(context.Context, *stratumn_node_app_indigo_store.LinkHash) (*stratumn_node_app_indigo_store.Segment, error)
	// Find segments.
	FindSegments(context.Context, *SegmentFilter) (*stratumn_node_app_indigo_store.Segments, error)
	// Get map IDs.
	GetMapIDs(context.Context, *MapFilter) (*MapIDs, error)
	// Add evidence to a segment.
	AddEvidence(context.Context, *AddEvidenceReq) (*AddEvidenceResp, error)
	// Get segment evidences.
	GetEvidences(context.Context, *stratumn_node_app_indigo_store.LinkHash) (*stratumn_node_app_indigo_store.Evidences, error)
}

func RegisterIndigoStoreServer(s *grpc.Server, srv IndigoStoreServer) {
	s.RegisterService(&_IndigoStore_serviceDesc, srv)
}

func _IndigoStore_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndigoStoreServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stratumn.node.app.indigo.store.grpc.IndigoStore/GetInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndigoStoreServer).GetInfo(ctx, req.(*InfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndigoStore_CreateLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(stratumn_node_app_indigo_store.Link)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndigoStoreServer).CreateLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stratumn.node.app.indigo.store.grpc.IndigoStore/CreateLink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndigoStoreServer).CreateLink(ctx, req.(*stratumn_node_app_indigo_store.Link))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndigoStore_GetSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(stratumn_node_app_indigo_store.LinkHash)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndigoStoreServer).GetSegment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stratumn.node.app.indigo.store.grpc.IndigoStore/GetSegment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndigoStoreServer).GetSegment(ctx, req.(*stratumn_node_app_indigo_store.LinkHash))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndigoStore_FindSegments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SegmentFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndigoStoreServer).FindSegments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stratumn.node.app.indigo.store.grpc.IndigoStore/FindSegments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndigoStoreServer).FindSegments(ctx, req.(*SegmentFilter))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndigoStore_GetMapIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MapFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndigoStoreServer).GetMapIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stratumn.node.app.indigo.store.grpc.IndigoStore/GetMapIDs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndigoStoreServer).GetMapIDs(ctx, req.(*MapFilter))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndigoStore_AddEvidence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddEvidenceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndigoStoreServer).AddEvidence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stratumn.node.app.indigo.store.grpc.IndigoStore/AddEvidence",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndigoStoreServer).AddEvidence(ctx, req.(*AddEvidenceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndigoStore_GetEvidences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(stratumn_node_app_indigo_store.LinkHash)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndigoStoreServer).GetEvidences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stratumn.node.app.indigo.store.grpc.IndigoStore/GetEvidences",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndigoStoreServer).GetEvidences(ctx, req.(*stratumn_node_app_indigo_store.LinkHash))
	}
	return interceptor(ctx, in, info, handler)
}

var _IndigoStore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "stratumn.node.app.indigo.store.grpc.IndigoStore",
	HandlerType: (*IndigoStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _IndigoStore_GetInfo_Handler,
		},
		{
			MethodName: "CreateLink",
			Handler:    _IndigoStore_CreateLink_Handler,
		},
		{
			MethodName: "GetSegment",
			Handler:    _IndigoStore_GetSegment_Handler,
		},
		{
			MethodName: "FindSegments",
			Handler:    _IndigoStore_FindSegments_Handler,
		},
		{
			MethodName: "GetMapIDs",
			Handler:    _IndigoStore_GetMapIDs_Handler,
		},
		{
			MethodName: "AddEvidence",
			Handler:    _IndigoStore_AddEvidence_Handler,
		},
		{
			MethodName: "GetEvidences",
			Handler:    _IndigoStore_GetEvidences_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/stratumn/go-node/app/indigo/grpc/store/store.proto",
}

func (m *InfoReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *InfoReq) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func (m *InfoResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *InfoResp) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Data) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintStore(dAtA, i, uint64(len(m.Data)))
		i += copy(dAtA[i:], m.Data)
	}
	return i, nil
}

func (m *SegmentFilter) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SegmentFilter) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Data) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintStore(dAtA, i, uint64(len(m.Data)))
		i += copy(dAtA[i:], m.Data)
	}
	return i, nil
}

func (m *MapIDs) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MapIDs) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.MapIds) > 0 {
		for _, s := range m.MapIds {
			dAtA[i] = 0xa
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	return i, nil
}

func (m *MapFilter) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MapFilter) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Data) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintStore(dAtA, i, uint64(len(m.Data)))
		i += copy(dAtA[i:], m.Data)
	}
	return i, nil
}

func (m *AddEvidenceReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AddEvidenceReq) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.LinkHash != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintStore(dAtA, i, uint64(m.LinkHash.Size()))
		n1, err := m.LinkHash.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if m.Evidence != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintStore(dAtA, i, uint64(m.Evidence.Size()))
		n2, err := m.Evidence.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	return i, nil
}

func (m *AddEvidenceResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AddEvidenceResp) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func encodeVarintStore(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *InfoReq) Size() (n int) {
	var l int
	_ = l
	return n
}

func (m *InfoResp) Size() (n int) {
	var l int
	_ = l
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovStore(uint64(l))
	}
	return n
}

func (m *SegmentFilter) Size() (n int) {
	var l int
	_ = l
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovStore(uint64(l))
	}
	return n
}

func (m *MapIDs) Size() (n int) {
	var l int
	_ = l
	if len(m.MapIds) > 0 {
		for _, s := range m.MapIds {
			l = len(s)
			n += 1 + l + sovStore(uint64(l))
		}
	}
	return n
}

func (m *MapFilter) Size() (n int) {
	var l int
	_ = l
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovStore(uint64(l))
	}
	return n
}

func (m *AddEvidenceReq) Size() (n int) {
	var l int
	_ = l
	if m.LinkHash != nil {
		l = m.LinkHash.Size()
		n += 1 + l + sovStore(uint64(l))
	}
	if m.Evidence != nil {
		l = m.Evidence.Size()
		n += 1 + l + sovStore(uint64(l))
	}
	return n
}

func (m *AddEvidenceResp) Size() (n int) {
	var l int
	_ = l
	return n
}

func sovStore(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozStore(x uint64) (n int) {
	return sovStore(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *InfoReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStore
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: InfoReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: InfoReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipStore(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthStore
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *InfoResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStore
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: InfoResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: InfoResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthStore
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStore(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthStore
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SegmentFilter) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStore
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SegmentFilter: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SegmentFilter: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthStore
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStore(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthStore
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MapIDs) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStore
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MapIDs: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MapIDs: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MapIds", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStore
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MapIds = append(m.MapIds, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStore(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthStore
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MapFilter) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStore
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MapFilter: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MapFilter: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthStore
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStore(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthStore
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AddEvidenceReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStore
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AddEvidenceReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AddEvidenceReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LinkHash", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStore
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LinkHash == nil {
				m.LinkHash = &stratumn_node_app_indigo_store.LinkHash{}
			}
			if err := m.LinkHash.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Evidence", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStore
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Evidence == nil {
				m.Evidence = &stratumn_node_app_indigo_store.Evidence{}
			}
			if err := m.Evidence.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStore(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthStore
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AddEvidenceResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStore
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AddEvidenceResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AddEvidenceResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipStore(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthStore
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipStore(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowStore
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStore
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStore
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthStore
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowStore
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipStore(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthStore = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowStore   = fmt.Errorf("proto: integer overflow")
)

func init() {
	proto.RegisterFile("github.com/stratumn/go-node/app/indigo/grpc/store/store.proto", fileDescriptorStore)
}

var fileDescriptorStore = []byte{
	// 709 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0x4f, 0x6b, 0x13, 0x4d,
	0x18, 0x7f, 0xf7, 0x7d, 0x5f, 0x9a, 0x64, 0x52, 0x95, 0x0e, 0xb6, 0x4c, 0x57, 0x1a, 0xa7, 0x8b,
	0x42, 0x2d, 0x64, 0x83, 0xa9, 0x4a, 0xab, 0x78, 0x68, 0x5a, 0x1b, 0x53, 0xac, 0x85, 0xf4, 0xe6,
	0xa5, 0x4c, 0xb2, 0xd3, 0x64, 0x68, 0x76, 0x66, 0xba, 0x33, 0xad, 0xf5, 0x24, 0xec, 0xd1, 0x83,
	0x27, 0x0f, 0x82, 0xb7, 0x08, 0x9e, 0xbd, 0xec, 0x29, 0x5f, 0xc0, 0xa3, 0x1f, 0x41, 0xe2, 0x17,
	0x91, 0xfd, 0xd7, 0x66, 0x51, 0x30, 0xdb, 0x43, 0x96, 0x2c, 0x3c, 0xbf, 0x3f, 0xf3, 0x3c, 0xbf,
	0x67, 0x16, 0x6c, 0xf5, 0x98, 0xee, 0x9f, 0x76, 0xec, 0xae, 0x70, 0x6b, 0x4a, 0x7b, 0x44, 0x9f,
	0xba, 0xbc, 0xd6, 0x13, 0x55, 0xc6, 0x1d, 0xd6, 0x13, 0x5c, 0x38, 0xb4, 0x46, 0xa4, 0xac, 0xc5,
	0xaf, 0xb5, 0x9e, 0x27, 0xbb, 0x35, 0xa5, 0x85, 0x47, 0xe3, 0xa7, 0x2d, 0x3d, 0xa1, 0x05, 0xbc,
	0x97, 0x22, 0xed, 0x4b, 0x98, 0x4d, 0xa4, 0x4c, 0x5e, 0xed, 0xb8, 0x36, 0x04, 0x9b, 0xeb, 0x7f,
	0xd7, 0xeb, 0x0e, 0x58, 0x2c, 0x44, 0xcf, 0x75, 0xf8, 0x8b, 0x45, 0xcc, 0x7c, 0x4e, 0x65, 0x27,
	0xf5, 0x49, 0x7b, 0x2e, 0xe5, 0x09, 0x89, 0x55, 0x02, 0x85, 0x16, 0x3f, 0x12, 0x6d, 0x7a, 0x62,
	0x35, 0x40, 0x31, 0xfe, 0xab, 0x24, 0x7c, 0x04, 0xfe, 0x77, 0x88, 0x26, 0xc8, 0xc0, 0xc6, 0xca,
	0x6c, 0xc3, 0x1a, 0x8e, 0x50, 0x65, 0xf7, 0x60, 0xff, 0x65, 0x95, 0xf2, 0xae, 0x70, 0xa8, 0x83,
	0x23, 0x2a, 0xcc, 0xf8, 0x91, 0xf0, 0x5c, 0xa2, 0x99, 0xe0, 0xed, 0xa8, 0xde, 0xda, 0x05, 0xd7,
	0x0e, 0x62, 0xfe, 0x1d, 0x36, 0xd0, 0xd4, 0x83, 0x1b, 0x19, 0xa2, 0xbb, 0xc3, 0x11, 0x5a, 0xce,
	0x12, 0xc5, 0xd5, 0xf8, 0x28, 0x2a, 0xc7, 0x9d, 0x37, 0x9a, 0xaa, 0x84, 0xcb, 0x06, 0x33, 0x7b,
	0x44, 0xb6, 0xb6, 0x15, 0xbc, 0x03, 0x0a, 0x2e, 0x91, 0x87, 0xcc, 0x51, 0xc8, 0xc0, 0xff, 0xad,
	0x94, 0x1a, 0xe5, 0xe1, 0x08, 0x15, 0xf6, 0x88, 0xc4, 0xad, 0x6d, 0xd5, 0x9e, 0x71, 0x89, 0x6c,
	0x39, 0xca, 0x6a, 0x80, 0xd2, 0x1e, 0x91, 0x89, 0xee, 0xc3, 0x8c, 0xee, 0xf2, 0x70, 0x84, 0x96,
	0x32, 0xba, 0x2e, 0x91, 0x7f, 0xd2, 0x1c, 0x1b, 0xe0, 0xfa, 0xa6, 0xe3, 0x3c, 0x3b, 0x63, 0x0e,
	0xe5, 0x5d, 0xda, 0xa6, 0x27, 0xb0, 0x0b, 0x4a, 0x03, 0xc6, 0x8f, 0x0f, 0xfb, 0x44, 0xf5, 0x23,
	0xba, 0x72, 0xdd, 0xb6, 0xa7, 0x9a, 0xef, 0x0b, 0xc6, 0x8f, 0x9f, 0x13, 0xd5, 0x6f, 0x2c, 0x0c,
	0x47, 0x08, 0xae, 0xd5, 0xab, 0x91, 0x12, 0x0e, 0xd9, 0x70, 0xc8, 0xd6, 0x2e, 0x0e, 0x92, 0x0a,
	0x78, 0x0c, 0x8a, 0x34, 0xd1, 0x44, 0xff, 0xe6, 0xd1, 0x48, 0x9d, 0x36, 0x6e, 0x0f, 0x47, 0xe8,
	0x56, 0xe6, 0x88, 0x29, 0x61, 0x72, 0xc0, 0x0b, 0x01, 0x6b, 0x0e, 0xdc, 0xc8, 0x9c, 0x51, 0xc9,
	0xfa, 0xd7, 0x22, 0x28, 0xb7, 0x22, 0xde, 0x83, 0x90, 0x16, 0x7e, 0x31, 0x40, 0xa1, 0x49, 0x75,
	0x98, 0x07, 0x58, 0xb7, 0xa7, 0x4e, 0xb3, 0x9d, 0x64, 0xc9, 0x5c, 0xcb, 0x8d, 0x51, 0xd2, 0xaa,
	0xfb, 0x01, 0xb2, 0x9b, 0x54, 0x4f, 0xe6, 0x0a, 0x93, 0x8e, 0x38, 0xd5, 0x58, 0xf7, 0x29, 0x8e,
	0xfd, 0xe1, 0xc8, 0x20, 0x56, 0xd4, 0x3b, 0x63, 0x5d, 0x0a, 0xdf, 0x02, 0xb0, 0xe5, 0x51, 0xa2,
	0x69, 0xd8, 0x6c, 0xb8, 0x3a, 0xfd, 0x60, 0xcc, 0x9c, 0x43, 0xb4, 0xe6, 0xfd, 0x00, 0xcd, 0xc5,
	0x5a, 0x98, 0x60, 0x4e, 0x5f, 0x47, 0x83, 0x84, 0x9f, 0x0c, 0x00, 0x9a, 0x54, 0x27, 0xa9, 0x87,
	0x39, 0x59, 0xcd, 0xea, 0x74, 0xf5, 0x09, 0xbd, 0x65, 0xfb, 0x01, 0x5a, 0x0d, 0x5b, 0x44, 0x38,
	0xa6, 0xe7, 0x4c, 0x69, 0xc6, 0x7b, 0x97, 0x3b, 0xe4, 0x09, 0x17, 0x33, 0x3d, 0x91, 0x30, 0xf8,
	0xc1, 0x00, 0xb3, 0x3b, 0x8c, 0x3b, 0x09, 0x5e, 0xc1, 0xf5, 0x1c, 0x83, 0xc9, 0x6c, 0xf2, 0xb4,
	0xfd, 0x4a, 0x95, 0x2c, 0xd3, 0x0f, 0xd0, 0x42, 0xa8, 0xfd, 0x9b, 0x51, 0x05, 0xdf, 0x1b, 0xa0,
	0xd4, 0xa4, 0x3a, 0x59, 0xef, 0x07, 0x39, 0x3c, 0x5d, 0x6c, 0xb8, 0x79, 0x3f, 0x1f, 0xaa, 0xb5,
	0xad, 0x2c, 0xe4, 0x07, 0xe8, 0x66, 0xd8, 0xbd, 0x0b, 0x47, 0x6e, 0x7c, 0x87, 0xc0, 0xcf, 0x06,
	0x28, 0x4f, 0xec, 0x04, 0xdc, 0xc8, 0x41, 0x9e, 0xbd, 0x2f, 0xcc, 0xc7, 0x57, 0x85, 0x2a, 0x69,
	0x2d, 0xf9, 0x01, 0x5a, 0xdc, 0x74, 0x26, 0x76, 0x57, 0x0b, 0x4c, 0xd2, 0xbe, 0xc1, 0x77, 0x06,
	0x98, 0x6d, 0x52, 0x9d, 0x42, 0x54, 0xee, 0xb4, 0xd5, 0xf2, 0x5d, 0x2a, 0xca, 0x5a, 0xf4, 0x03,
	0x34, 0x1f, 0x76, 0x2c, 0xcd, 0x58, 0x6a, 0x4c, 0x35, 0xf6, 0xbf, 0x8d, 0x2b, 0xc6, 0xf7, 0x71,
	0xc5, 0xf8, 0x31, 0xae, 0x18, 0x1f, 0x7f, 0x56, 0xfe, 0x79, 0xf5, 0xf4, 0x8a, 0x9f, 0xce, 0x27,
	0xd1, 0xb3, 0x33, 0x13, 0x7d, 0x91, 0xd6, 0x7e, 0x05, 0x00, 0x00, 0xff, 0xff, 0xbe, 0xc4, 0xf6,
	0xc5, 0x82, 0x07, 0x00, 0x00,
}
