// Copyright © 2017-2018 Stratumn SAS
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

package transaction

import (
	"testing"

	"github.com/stratumn/go-node/app/coin/pb"
	"github.com/stretchr/testify/require"

	ic "gx/ipfs/QmPvyPwuCgJ7pDmrKDxRtsScJgBaM5h4EpRL2qQJsmXf4n/go-libp2p-crypto"
	peer "gx/ipfs/QmQsErDt8Qgw1XrsXf2BpEzDgGWtB1YLsTAARBup5b6B9W/go-libp2p-peer"
)

var txSenderPrivateKey ic.PrivKey
var txSenderPublicKey ic.PubKey

// TxSenderPID is the sender in transactions generated by NewTransaction.
var TxSenderPID peer.ID

// TxRecipientPID is the recipient in transactions generated by NewTransaction.
var TxRecipientPID peer.ID

func init() {
	sk, pk, err := ic.GenerateKeyPair(ic.Ed25519, 0)
	if err != nil {
		panic(err)
	}

	txSenderPrivateKey = sk
	txSenderPublicKey = pk

	pid, err := peer.IDFromPrivateKey(txSenderPrivateKey)
	if err != nil {
		panic(err)
	}

	TxSenderPID = pid

	pid, err = peer.IDB58Decode("QmYgPDzgtjRQFC4poxTD8fgVnVVf3wHQPjrmyph8Wy8ZmQ")
	if err != nil {
		panic(err)
	}

	TxRecipientPID = pid
}

// NewKeyPair returns key pair and peer ID.
func NewKeyPair() (ic.PrivKey, ic.PubKey, []byte, error) {
	sk, pk, err := ic.GenerateKeyPair(ic.Ed25519, 0)
	if err != nil {
		return nil, nil, nil, err
	}

	pid, err := peer.IDFromPrivateKey(sk)
	if err != nil {
		return nil, nil, nil, err
	}

	return sk, pk, []byte(pid), nil
}

// NewTransaction creates a properly signed transaction.
func NewTransaction(t *testing.T, value, fee, nonce uint64) *pb.Transaction {
	tx := &pb.Transaction{
		From:  []byte(TxSenderPID),
		To:    []byte(TxRecipientPID),
		Value: value,
		Fee:   fee,
		Nonce: nonce,
	}

	b, err := tx.Marshal()
	require.NoError(t, err, "tx.Marshal()")

	sig, err := txSenderPrivateKey.Sign(b)
	require.NoError(t, err, "testSenderPrivateKey.Sign(b)")

	pk, err := txSenderPublicKey.Bytes()
	require.NoError(t, err, "testSenderPublicKey.Bytes()")

	tx.Signature = &pb.Signature{
		KeyType:   pb.KeyType_Ed25519,
		PublicKey: pk,
		Signature: sig,
	}

	return tx
}

// NewTransactions creates a set of random transactions.
func NewTransactions(t *testing.T, txCount int) []*pb.Transaction {
	txs := make([]*pb.Transaction, txCount)
	for i := 0; i < txCount; i++ {
		txs[i] = NewTransaction(t, 4, 2, uint64(i))
	}
	return txs
}

// NewRewardTransaction creates a new reward transaction.
func NewRewardTransaction(t *testing.T, value uint64) *pb.Transaction {
	return &pb.Transaction{
		To:    []byte(TxRecipientPID),
		Value: value,
	}
}
