// Code generated by MockGen. DO NOT EDIT.
// Source: gx/ipfs/QmXoz9o2PT3tEzf7hicegwex5UgVP54n3k82K7jrWFyN86/go-libp2p-net (interfaces: Network)

package mockbootstrap

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	goprocess "gx/ipfs/QmSF8fPo3jgVBAy8fpdjjYqgG87dkJgUprRBHRd2tmfgpP/goprocess"
	go_multiaddr "gx/ipfs/QmWWQ2Txc2c6tqjsBpzg5Ar652cHPGNsQQp2SejkNmkUMb/go-multiaddr"
	go_libp2p_net "gx/ipfs/QmXoz9o2PT3tEzf7hicegwex5UgVP54n3k82K7jrWFyN86/go-libp2p-net"
	go_libp2p_peer "gx/ipfs/QmcJukH2sAFjY3HdBKq35WDzWoL3UUu2gt9wdfqZTUyM74/go-libp2p-peer"
	go_libp2p_peerstore "gx/ipfs/QmdeiKhUy1TVGBaKxt7y1QmBDLBdisSrLJ1x58Eoj4PXUh/go-libp2p-peerstore"
	reflect "reflect"
)

// MockNetwork is a mock of Network interface
type MockNetwork struct {
	ctrl     *gomock.Controller
	recorder *MockNetworkMockRecorder
}

// MockNetworkMockRecorder is the mock recorder for MockNetwork
type MockNetworkMockRecorder struct {
	mock *MockNetwork
}

// NewMockNetwork creates a new mock instance
func NewMockNetwork(ctrl *gomock.Controller) *MockNetwork {
	mock := &MockNetwork{ctrl: ctrl}
	mock.recorder = &MockNetworkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockNetwork) EXPECT() *MockNetworkMockRecorder {
	return _m.recorder
}

// Close mocks base method
func (_m *MockNetwork) Close() error {
	ret := _m.ctrl.Call(_m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close
func (_mr *MockNetworkMockRecorder) Close() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Close", reflect.TypeOf((*MockNetwork)(nil).Close))
}

// ClosePeer mocks base method
func (_m *MockNetwork) ClosePeer(_param0 go_libp2p_peer.ID) error {
	ret := _m.ctrl.Call(_m, "ClosePeer", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClosePeer indicates an expected call of ClosePeer
func (_mr *MockNetworkMockRecorder) ClosePeer(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "ClosePeer", reflect.TypeOf((*MockNetwork)(nil).ClosePeer), arg0)
}

// Connectedness mocks base method
func (_m *MockNetwork) Connectedness(_param0 go_libp2p_peer.ID) go_libp2p_net.Connectedness {
	ret := _m.ctrl.Call(_m, "Connectedness", _param0)
	ret0, _ := ret[0].(go_libp2p_net.Connectedness)
	return ret0
}

// Connectedness indicates an expected call of Connectedness
func (_mr *MockNetworkMockRecorder) Connectedness(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Connectedness", reflect.TypeOf((*MockNetwork)(nil).Connectedness), arg0)
}

// Conns mocks base method
func (_m *MockNetwork) Conns() []go_libp2p_net.Conn {
	ret := _m.ctrl.Call(_m, "Conns")
	ret0, _ := ret[0].([]go_libp2p_net.Conn)
	return ret0
}

// Conns indicates an expected call of Conns
func (_mr *MockNetworkMockRecorder) Conns() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Conns", reflect.TypeOf((*MockNetwork)(nil).Conns))
}

// ConnsToPeer mocks base method
func (_m *MockNetwork) ConnsToPeer(_param0 go_libp2p_peer.ID) []go_libp2p_net.Conn {
	ret := _m.ctrl.Call(_m, "ConnsToPeer", _param0)
	ret0, _ := ret[0].([]go_libp2p_net.Conn)
	return ret0
}

// ConnsToPeer indicates an expected call of ConnsToPeer
func (_mr *MockNetworkMockRecorder) ConnsToPeer(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "ConnsToPeer", reflect.TypeOf((*MockNetwork)(nil).ConnsToPeer), arg0)
}

// DialPeer mocks base method
func (_m *MockNetwork) DialPeer(_param0 context.Context, _param1 go_libp2p_peer.ID) (go_libp2p_net.Conn, error) {
	ret := _m.ctrl.Call(_m, "DialPeer", _param0, _param1)
	ret0, _ := ret[0].(go_libp2p_net.Conn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DialPeer indicates an expected call of DialPeer
func (_mr *MockNetworkMockRecorder) DialPeer(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "DialPeer", reflect.TypeOf((*MockNetwork)(nil).DialPeer), arg0, arg1)
}

// InterfaceListenAddresses mocks base method
func (_m *MockNetwork) InterfaceListenAddresses() ([]go_multiaddr.Multiaddr, error) {
	ret := _m.ctrl.Call(_m, "InterfaceListenAddresses")
	ret0, _ := ret[0].([]go_multiaddr.Multiaddr)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InterfaceListenAddresses indicates an expected call of InterfaceListenAddresses
func (_mr *MockNetworkMockRecorder) InterfaceListenAddresses() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "InterfaceListenAddresses", reflect.TypeOf((*MockNetwork)(nil).InterfaceListenAddresses))
}

// Listen mocks base method
func (_m *MockNetwork) Listen(_param0 ...go_multiaddr.Multiaddr) error {
	_s := []interface{}{}
	for _, _x := range _param0 {
		_s = append(_s, _x)
	}
	ret := _m.ctrl.Call(_m, "Listen", _s...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Listen indicates an expected call of Listen
func (_mr *MockNetworkMockRecorder) Listen(arg0 ...interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Listen", reflect.TypeOf((*MockNetwork)(nil).Listen), arg0...)
}

// ListenAddresses mocks base method
func (_m *MockNetwork) ListenAddresses() []go_multiaddr.Multiaddr {
	ret := _m.ctrl.Call(_m, "ListenAddresses")
	ret0, _ := ret[0].([]go_multiaddr.Multiaddr)
	return ret0
}

// ListenAddresses indicates an expected call of ListenAddresses
func (_mr *MockNetworkMockRecorder) ListenAddresses() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "ListenAddresses", reflect.TypeOf((*MockNetwork)(nil).ListenAddresses))
}

// LocalPeer mocks base method
func (_m *MockNetwork) LocalPeer() go_libp2p_peer.ID {
	ret := _m.ctrl.Call(_m, "LocalPeer")
	ret0, _ := ret[0].(go_libp2p_peer.ID)
	return ret0
}

// LocalPeer indicates an expected call of LocalPeer
func (_mr *MockNetworkMockRecorder) LocalPeer() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "LocalPeer", reflect.TypeOf((*MockNetwork)(nil).LocalPeer))
}

// NewStream mocks base method
func (_m *MockNetwork) NewStream(_param0 context.Context, _param1 go_libp2p_peer.ID) (go_libp2p_net.Stream, error) {
	ret := _m.ctrl.Call(_m, "NewStream", _param0, _param1)
	ret0, _ := ret[0].(go_libp2p_net.Stream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewStream indicates an expected call of NewStream
func (_mr *MockNetworkMockRecorder) NewStream(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "NewStream", reflect.TypeOf((*MockNetwork)(nil).NewStream), arg0, arg1)
}

// Notify mocks base method
func (_m *MockNetwork) Notify(_param0 go_libp2p_net.Notifiee) {
	_m.ctrl.Call(_m, "Notify", _param0)
}

// Notify indicates an expected call of Notify
func (_mr *MockNetworkMockRecorder) Notify(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Notify", reflect.TypeOf((*MockNetwork)(nil).Notify), arg0)
}

// Peers mocks base method
func (_m *MockNetwork) Peers() []go_libp2p_peer.ID {
	ret := _m.ctrl.Call(_m, "Peers")
	ret0, _ := ret[0].([]go_libp2p_peer.ID)
	return ret0
}

// Peers indicates an expected call of Peers
func (_mr *MockNetworkMockRecorder) Peers() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Peers", reflect.TypeOf((*MockNetwork)(nil).Peers))
}

// Peerstore mocks base method
func (_m *MockNetwork) Peerstore() go_libp2p_peerstore.Peerstore {
	ret := _m.ctrl.Call(_m, "Peerstore")
	ret0, _ := ret[0].(go_libp2p_peerstore.Peerstore)
	return ret0
}

// Peerstore indicates an expected call of Peerstore
func (_mr *MockNetworkMockRecorder) Peerstore() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Peerstore", reflect.TypeOf((*MockNetwork)(nil).Peerstore))
}

// Process mocks base method
func (_m *MockNetwork) Process() goprocess.Process {
	ret := _m.ctrl.Call(_m, "Process")
	ret0, _ := ret[0].(goprocess.Process)
	return ret0
}

// Process indicates an expected call of Process
func (_mr *MockNetworkMockRecorder) Process() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Process", reflect.TypeOf((*MockNetwork)(nil).Process))
}

// SetConnHandler mocks base method
func (_m *MockNetwork) SetConnHandler(_param0 go_libp2p_net.ConnHandler) {
	_m.ctrl.Call(_m, "SetConnHandler", _param0)
}

// SetConnHandler indicates an expected call of SetConnHandler
func (_mr *MockNetworkMockRecorder) SetConnHandler(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "SetConnHandler", reflect.TypeOf((*MockNetwork)(nil).SetConnHandler), arg0)
}

// SetStreamHandler mocks base method
func (_m *MockNetwork) SetStreamHandler(_param0 go_libp2p_net.StreamHandler) {
	_m.ctrl.Call(_m, "SetStreamHandler", _param0)
}

// SetStreamHandler indicates an expected call of SetStreamHandler
func (_mr *MockNetworkMockRecorder) SetStreamHandler(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "SetStreamHandler", reflect.TypeOf((*MockNetwork)(nil).SetStreamHandler), arg0)
}

// StopNotify mocks base method
func (_m *MockNetwork) StopNotify(_param0 go_libp2p_net.Notifiee) {
	_m.ctrl.Call(_m, "StopNotify", _param0)
}

// StopNotify indicates an expected call of StopNotify
func (_mr *MockNetworkMockRecorder) StopNotify(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "StopNotify", reflect.TypeOf((*MockNetwork)(nil).StopNotify), arg0)
}
